leaf_size: 0.0075

radius: 6
filter_min: 0
filter_max: 4
distance_threshold: 7
point_color_threshold: 3
region_color_threshold: 5
tolerance: 0.01

min_cluster_size: 20
max_cluster_size: 1000

min_neighbors: 4
outlier_radius: 0.01

exclusion_padding: 0.01
sample_size: 100
